/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examendiegovarela;

import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Examen1DiegoVarela extends javax.swing.JFrame {
Random random=new Random();
    /**
     * Creates new form Examen1DiegoVarela
     */
    public Examen1DiegoVarela() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tutor = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jb_clase = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        jt_clase = new javax.swing.JTextField();
        Estudiante = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jt_aprendizaje = new javax.swing.JTextField();
        jb_guardarestudiante = new javax.swing.JButton();
        sesiontutor = new javax.swing.JFrame();
        Iniciarsesiontutor = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jt_usuario2 = new javax.swing.JTextField();
        jt_contraseña2 = new javax.swing.JTextField();
        sesionestudiante = new javax.swing.JFrame();
        Iniciarsesionestu = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jt_usuario3 = new javax.swing.JTextField();
        jt_contraseña3 = new javax.swing.JTextField();
        ventanatutor = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tutores = new javax.swing.JTable();
        jb_modificar = new javax.swing.JButton();
        jb_tutoria = new javax.swing.JButton();
        jb_salir2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jt_nom = new javax.swing.JTextField();
        jt_ed = new javax.swing.JTextField();
        jt_carr = new javax.swing.JTextField();
        jt_naci = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jt_no = new javax.swing.JTextField();
        jt_usua = new javax.swing.JTextField();
        jt_contra = new javax.swing.JTextField();
        jt_gan = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        ventanaestudiante = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Edad1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jt_no1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jt_usua1 = new javax.swing.JTextField();
        jt_nom1 = new javax.swing.JTextField();
        jt_contra1 = new javax.swing.JTextField();
        jt_ed1 = new javax.swing.JTextField();
        jt_apre = new javax.swing.JTextField();
        jt_carr1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        estudiantes = new javax.swing.JTable();
        jt_naci1 = new javax.swing.JTextField();
        jb_modificarestu = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jb_tutoria1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jb_salir3 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        Tutorias = new javax.swing.JFrame();
        jd_fecha = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jb_creartuto = new javax.swing.JButton();
        jt_aula = new javax.swing.JTextField();
        jt_tema1 = new javax.swing.JTextField();
        jt_hora = new javax.swing.JTextField();
        cb_tutor = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        simulartuto = new javax.swing.JFrame();
        cb_sim = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jt_edad = new javax.swing.JTextField();
        jt_carrera = new javax.swing.JTextField();
        jt_lugar = new javax.swing.JTextField();
        jt_numero = new javax.swing.JTextField();
        jt_usuario = new javax.swing.JTextField();
        jt_contraseña = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jb_iniciartutor = new javax.swing.JButton();
        jb_inicarestudiante = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jt_cla = new javax.swing.JTextField();
        jt_cono = new javax.swing.JTextField();
        jt_tema = new javax.swing.JTextField();
        jt_puntaje = new javax.swing.JTextField();
        jb_exam = new javax.swing.JButton();

        jLabel9.setText("Agregar clases:");

        jb_clase.setText("Agregar");
        jb_clase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_claseMouseClicked(evt);
            }
        });

        jb_salir.setText("Salir");
        jb_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tutorLayout = new javax.swing.GroupLayout(tutor.getContentPane());
        tutor.getContentPane().setLayout(tutorLayout);
        tutorLayout.setHorizontalGroup(
            tutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(tutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tutorLayout.createSequentialGroup()
                        .addComponent(jb_clase)
                        .addGap(65, 65, 65)
                        .addComponent(jb_salir))
                    .addGroup(tutorLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jt_clase, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        tutorLayout.setVerticalGroup(
            tutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(tutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jt_clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(tutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_clase)
                    .addComponent(jb_salir))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jLabel10.setText("Nivel de aprendizaje:");

        jb_guardarestudiante.setText("Guardar");
        jb_guardarestudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarestudianteMouseClicked(evt);
            }
        });
        jb_guardarestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarestudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EstudianteLayout = new javax.swing.GroupLayout(Estudiante.getContentPane());
        Estudiante.getContentPane().setLayout(EstudianteLayout);
        EstudianteLayout.setHorizontalGroup(
            EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstudianteLayout.createSequentialGroup()
                .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EstudianteLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jt_aprendizaje, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EstudianteLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jb_guardarestudiante)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        EstudianteLayout.setVerticalGroup(
            EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstudianteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jt_aprendizaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jb_guardarestudiante)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        Iniciarsesiontutor.setText("Iniciar sesion");
        Iniciarsesiontutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarsesiontutorMouseClicked(evt);
            }
        });

        jLabel12.setText("Usuario: ");

        jLabel13.setText("Contraseña: ");

        javax.swing.GroupLayout sesiontutorLayout = new javax.swing.GroupLayout(sesiontutor.getContentPane());
        sesiontutor.getContentPane().setLayout(sesiontutorLayout);
        sesiontutorLayout.setHorizontalGroup(
            sesiontutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sesiontutorLayout.createSequentialGroup()
                .addGroup(sesiontutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sesiontutorLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(Iniciarsesiontutor))
                    .addGroup(sesiontutorLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(sesiontutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(sesiontutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_usuario2)
                            .addComponent(jt_contraseña2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        sesiontutorLayout.setVerticalGroup(
            sesiontutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sesiontutorLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(sesiontutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jt_usuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(sesiontutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jt_contraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Iniciarsesiontutor)
                .addGap(103, 103, 103))
        );

        Iniciarsesionestu.setText("Iniciar sesion");
        Iniciarsesionestu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarsesionestuMouseClicked(evt);
            }
        });

        jLabel14.setText("Usuario: ");

        jLabel15.setText("Contraseña: ");

        javax.swing.GroupLayout sesionestudianteLayout = new javax.swing.GroupLayout(sesionestudiante.getContentPane());
        sesionestudiante.getContentPane().setLayout(sesionestudianteLayout);
        sesionestudianteLayout.setHorizontalGroup(
            sesionestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sesionestudianteLayout.createSequentialGroup()
                .addGroup(sesionestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sesionestudianteLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(Iniciarsesionestu))
                    .addGroup(sesionestudianteLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(sesionestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(sesionestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_usuario3)
                            .addComponent(jt_contraseña3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        sesionestudianteLayout.setVerticalGroup(
            sesionestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sesionestudianteLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(sesionestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jt_usuario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(sesionestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jt_contraseña3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Iniciarsesionestu)
                .addGap(103, 103, 103))
        );

        tutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Carrera", "Lugar de nacimiento", "Numero de cuenta", "Usuario", "Contraseña", "Ganancias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tutores);

        jb_modificar.setText("Modificar");
        jb_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarMouseClicked(evt);
            }
        });

        jb_tutoria.setText("Tutoria");

        jb_salir2.setText("salir");
        jb_salir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salir2MouseClicked(evt);
            }
        });

        jLabel16.setText("Nombre:");

        Edad.setText("Edad:");

        jLabel18.setText("Carrera:");

        jLabel19.setText("Lugar de nacimiento: ");

        jLabel20.setText("Numero de cuenta:");

        jLabel21.setText("Usuario:");

        jLabel22.setText("Contraseña:");

        jLabel23.setText("Ganancias:");

        jButton3.setText("Examen");

        javax.swing.GroupLayout ventanatutorLayout = new javax.swing.GroupLayout(ventanatutor.getContentPane());
        ventanatutor.getContentPane().setLayout(ventanatutorLayout);
        ventanatutorLayout.setHorizontalGroup(
            ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(ventanatutorLayout.createSequentialGroup()
                .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanatutorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ventanatutorLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_nom)
                                .addGap(136, 136, 136))
                            .addGroup(ventanatutorLayout.createSequentialGroup()
                                .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ventanatutorLayout.createSequentialGroup()
                                        .addComponent(Edad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jt_ed, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ventanatutorLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jt_carr, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(105, 105, 105)))
                        .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ventanatutorLayout.createSequentialGroup()
                                .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ventanatutorLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jt_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ventanatutorLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jt_gan))))
                            .addGroup(ventanatutorLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_no, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ventanatutorLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_usua))))
                    .addGroup(ventanatutorLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jb_modificar)
                        .addGap(45, 45, 45)
                        .addComponent(jb_tutoria)
                        .addGap(50, 50, 50)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_salir2))
                    .addGroup(ventanatutorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_naci, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        ventanatutorLayout.setVerticalGroup(
            ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanatutorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_modificar)
                    .addComponent(jb_tutoria)
                    .addComponent(jb_salir2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jt_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanatutorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edad)
                            .addComponent(jt_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ventanatutorLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jt_usua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jt_carr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jt_gan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanatutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jt_naci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel17.setText("Nombre:");

        jLabel24.setText("Aprendizaje");

        Edad1.setText("Edad:");

        jLabel25.setText("Carrera:");

        jLabel26.setText("Lugar de nacimiento: ");

        estudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Carrera", "Lugar de nacimiento", "Numero de cuenta", "Usuario", "Contraseña", "Ganancias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(estudiantes);

        jb_modificarestu.setText("Modificar");
        jb_modificarestu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarestuMouseClicked(evt);
            }
        });

        jLabel27.setText("Numero de cuenta:");

        jb_tutoria1.setText("Tutoria");
        jb_tutoria1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_tutoria1MouseClicked(evt);
            }
        });
        jb_tutoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_tutoria1ActionPerformed(evt);
            }
        });

        jLabel28.setText("Usuario:");

        jb_salir3.setText("salir");
        jb_salir3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salir3MouseClicked(evt);
            }
        });

        jLabel29.setText("Contraseña:");

        javax.swing.GroupLayout ventanaestudianteLayout = new javax.swing.GroupLayout(ventanaestudiante.getContentPane());
        ventanaestudiante.getContentPane().setLayout(ventanaestudianteLayout);
        ventanaestudianteLayout.setHorizontalGroup(
            ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(ventanaestudianteLayout.createSequentialGroup()
                .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaestudianteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ventanaestudianteLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_nom1)
                                .addGap(136, 136, 136))
                            .addGroup(ventanaestudianteLayout.createSequentialGroup()
                                .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ventanaestudianteLayout.createSequentialGroup()
                                        .addComponent(Edad1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jt_ed1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ventanaestudianteLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jt_carr1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(105, 105, 105)))
                        .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ventanaestudianteLayout.createSequentialGroup()
                                .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel24))
                                .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ventanaestudianteLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jt_contra1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ventanaestudianteLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jt_apre))))
                            .addGroup(ventanaestudianteLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ventanaestudianteLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_usua1))))
                    .addGroup(ventanaestudianteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jb_modificarestu)
                        .addGap(45, 45, 45)
                        .addComponent(jb_tutoria1)
                        .addGap(40, 40, 40)
                        .addComponent(jb_salir3))
                    .addGroup(ventanaestudianteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_naci1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        ventanaestudianteLayout.setVerticalGroup(
            ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaestudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_modificarestu)
                    .addComponent(jb_tutoria1)
                    .addComponent(jb_salir3))
                .addGap(18, 18, 18)
                .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jt_nom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(jt_no1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaestudianteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edad1)
                            .addComponent(jt_ed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ventanaestudianteLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jt_usua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_contra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jt_carr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jt_apre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jt_naci1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel32.setText("Fecha:");

        jLabel35.setText("Aula:");

        jLabel36.setText("Tema :");

        jLabel37.setText("Hora:");

        jb_creartuto.setText("Crear");
        jb_creartuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_creartutoMouseClicked(evt);
            }
        });

        jLabel38.setText("Tutor:");

        javax.swing.GroupLayout TutoriasLayout = new javax.swing.GroupLayout(Tutorias.getContentPane());
        Tutorias.getContentPane().setLayout(TutoriasLayout);
        TutoriasLayout.setHorizontalGroup(
            TutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutoriasLayout.createSequentialGroup()
                .addGroup(TutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(TutoriasLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel38)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TutoriasLayout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(TutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(TutoriasLayout.createSequentialGroup()
                                    .addComponent(jLabel37)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(TutoriasLayout.createSequentialGroup()
                                    .addGroup(TutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel32)
                                        .addComponent(jLabel35))
                                    .addGroup(TutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(TutoriasLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(TutoriasLayout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jt_aula, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(TutoriasLayout.createSequentialGroup()
                                    .addComponent(jLabel36)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jt_tema1)))))
                    .addGroup(TutoriasLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jb_creartuto)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        TutoriasLayout.setVerticalGroup(
            TutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutoriasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(TutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32)
                    .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jt_aula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jt_tema1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(TutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(27, 27, 27)
                .addComponent(jb_creartuto)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        cb_sim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_simItemStateChanged(evt);
            }
        });

        jLabel39.setText("Tutorias: ");

        javax.swing.GroupLayout simulartutoLayout = new javax.swing.GroupLayout(simulartuto.getContentPane());
        simulartuto.getContentPane().setLayout(simulartutoLayout);
        simulartutoLayout.setHorizontalGroup(
            simulartutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simulartutoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addComponent(cb_sim, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        simulartutoLayout.setVerticalGroup(
            simulartutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simulartutoLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(simulartutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_sim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Edad:");

        jLabel3.setText("Carrera:");

        jLabel4.setText("Lugar de nacimiento:");

        jLabel5.setText("Numero de cuenta:");

        jLabel6.setText("Usuario:");

        jLabel7.setText("Contraseña:");

        jt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nombreActionPerformed(evt);
            }
        });

        jt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_edadActionPerformed(evt);
            }
        });

        jt_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_contraseñaActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo de alumno:");

        jButton1.setText("Tutor");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Estudiante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_nombre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_edad))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_carrera))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_numero))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_usuario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_contraseña)))
                        .addGap(55, 244, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jt_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear cuenta", jPanel1);

        jLabel11.setText("Ingresar como:");

        jb_iniciartutor.setText("Tutor");
        jb_iniciartutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_iniciartutorMouseClicked(evt);
            }
        });

        jb_inicarestudiante.setText("Estudiante");
        jb_inicarestudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_inicarestudianteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jb_iniciartutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jb_inicarestudiante)
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_iniciartutor)
                    .addComponent(jb_inicarestudiante))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", jPanel2);

        jLabel30.setText("Clase:");

        jLabel31.setText("Conocimiento requerido:");

        jLabel33.setText("Tema:");

        jLabel34.setText("Puntaje:");

        jb_exam.setText("Crear examen");
        jb_exam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_examMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jt_cono))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jt_cla))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(jt_tema))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_exam)
                            .addComponent(jt_puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jt_cla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jt_cono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jt_tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jt_puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jb_exam)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear examen", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_nombreActionPerformed

    private void jt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_edadActionPerformed

    private void jt_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_contraseñaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.tutor.pack();
        tutor.setVisible(true);
        tutor.setLocationRelativeTo(null);

    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_claseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_claseMouseClicked
        // TODO add your handling code here:
        String clase;
        Tutores t = new Tutores();
        clase = jt_clase.getText();
        t.getClases().add(clase);
        JOptionPane.showMessageDialog(null, "Clase agregada con exito");
        jt_clase.setText("");
    }//GEN-LAST:event_jb_claseMouseClicked

    private void jb_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirMouseClicked
        // TODO add your handling code here:
        String nombre, carrera, lugar, usuario, contraseña;
        int edad, numero;
        try {
            nombre = jt_nombre.getText();
            carrera = jt_carrera.getText();
            lugar = jt_lugar.getText();
            edad = Integer.parseInt(jt_edad.getText());
            numero = Integer.parseInt(jt_numero.getText());
            usuario = jt_nombre.getText();
            contraseña = jt_nombre.getText();
            Tutores t = new Tutores(0, 0, edad, nombre, edad, carrera, usuario, numero, usuario, contraseña);
            lista.add(t);
            JOptionPane.showMessageDialog(null, "Alumno creado con exito");
            Object[] show = {
                t.getNombre(),
                t.getEdad(), t.getCarrera(),
                t.getCarrera(),
                t.getNacimiento(), t.getNumcuenta(), t.getUsuario(), t.getContraseña(), t.getGanancias()
            };
            DefaultTableModel modelo = (DefaultTableModel) tutores.getModel();
            modelo.addRow(show);
            tutores.setModel(modelo);
            DefaultComboBoxModel mo=(DefaultComboBoxModel) cb_tutor.getModel();
            mo.addElement(t.getNombre());
            cb_tutor.setModel(mo);
            jt_nombre.setText("");
            jt_carrera.setText("");
            jt_edad.setText("");
            jt_contraseña.setText("");
            jt_usuario.setText("");
            jt_numero.setText("");
            jt_lugar.setText("");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Hubo un error y no se guardaron los datos contacte al administrador");
        }
        this.tutor.pack();
        tutor.setVisible(false);
    }//GEN-LAST:event_jb_salirMouseClicked

    private void jb_guardarestudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarestudianteMouseClicked
        // TODO add your handling code here:
        String nombre, carrera, lugar, usuario, contraseña;
        int edad, numero, aprendizaje;
        try {
            nombre = jt_nombre.getText();
            carrera = jt_carrera.getText();
            lugar = jt_lugar.getText();
            edad = Integer.parseInt(jt_edad.getText());
            numero = Integer.parseInt(jt_numero.getText());
            usuario = jt_nombre.getText();
            contraseña = jt_nombre.getText();
            aprendizaje = Integer.parseInt(jt_aprendizaje.getText());
            Estudiante t = new Estudiante(0, aprendizaje, nombre, edad, carrera, usuario, numero, usuario, contraseña);
            lista.add(t);
            JOptionPane.showMessageDialog(null, "Alumno creado con exito");
            Object[] show = {
                t.getNombre(),
                t.getEdad(), t.getCarrera(),
                t.getCarrera(),
                t.getNacimiento(), t.getNumcuenta(), t.getUsuario(), t.getContraseña(), t.getAprendizaje()
            };
            DefaultTableModel modelo = (DefaultTableModel) tutores.getModel();
            modelo.addRow(show);
            tutores.setModel(modelo);
            jt_nombre.setText("");
            jt_carrera.setText("");
            jt_edad.setText("");
            jt_contraseña.setText("");
            jt_usuario.setText("");
            jt_numero.setText("");
            jt_lugar.setText("");

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Hubo un error y no se guardaron los datos contacte al administrador");
        }
        this.tutor.pack();
        tutor.setVisible(false);
    }//GEN-LAST:event_jb_guardarestudianteMouseClicked

    private void jb_guardarestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarestudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_guardarestudianteActionPerformed

    private void jb_iniciartutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_iniciartutorMouseClicked
        // TODO add your handling code here:
        sesiontutor.pack();
        sesiontutor.setVisible(true);
    }//GEN-LAST:event_jb_iniciartutorMouseClicked

    private void jb_inicarestudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_inicarestudianteMouseClicked
        // TODO add your handling code here:
        this.sesionestudiante.pack();
        sesionestudiante.setVisible(true);
    }//GEN-LAST:event_jb_inicarestudianteMouseClicked

    private void IniciarsesionestuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarsesionestuMouseClicked
        // TODO add your handling code here:
        String usuario, contraseña;
        try {
            usuario = jt_usuario3.getText();
            contraseña = jt_contraseña3.getText();
            for (Alumnos alumnos : lista) {
                if (alumnos instanceof Estudiante) {
                    if (usuario == ((Estudiante) alumnos).getUsuario() && contraseña == ((Estudiante) alumnos).getContraseña()) {
                        this.ventanatutor.pack();
                        ventanatutor.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "El usuario o cjontraseña no existe en tutor");
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Ocurrio un problema consulte al administrador");
        }
    }//GEN-LAST:event_IniciarsesionestuMouseClicked

    private void jb_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarMouseClicked
        // TODO add your handling code here:
        if (tutores.getSelectedRow() >= 0) {
            DefaultTableModel model = (DefaultTableModel) tutores.getModel();
            ((Tutores) model.getValueAt(tutores.getSelectedRow(), 0)).setNombre(jt_nom.getText());
            ((Tutores) model.getValueAt(tutores.getSelectedRow(), 1)).setEdad(Integer.parseInt(jt_ed.getText()));
            ((Tutores) model.getValueAt(tutores.getSelectedRow(), 2)).setCarrera(jt_carr.getText());
            ((Tutores) model.getValueAt(tutores.getSelectedRow(), 3)).setNacimiento(jt_naci.getText());
            ((Tutores) model.getValueAt(tutores.getSelectedRow(), 4)).setNumcuenta(Integer.parseInt(jt_no.getText()));
            ((Tutores) model.getValueAt(tutores.getSelectedRow(), 5)).setUsuario(jt_usua.getText());
            ((Tutores) model.getValueAt(tutores.getSelectedRow(), 6)).setContraseña(jt_contra.getText());
            ((Tutores) model.getValueAt(tutores.getSelectedRow(), 7)).setGanancias(Integer.parseInt(jt_gan.getText()));
            tutores.setModel(model);

        }
    }//GEN-LAST:event_jb_modificarMouseClicked

    private void jb_modificarestuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarestuMouseClicked
        // TODO add your handling code here:
        if (tutores.getSelectedRow() >= 0) {
            DefaultTableModel model = (DefaultTableModel) tutores.getModel();
            ((Tutores) model.getValueAt(estudiantes.getSelectedRow(), 0)).setNombre(jt_nom1.getText());
            ((Tutores) model.getValueAt(estudiantes.getSelectedRow(), 1)).setEdad(Integer.parseInt(jt_ed1.getText()));
            ((Tutores) model.getValueAt(estudiantes.getSelectedRow(), 2)).setCarrera(jt_carr1.getText());
            ((Tutores) model.getValueAt(estudiantes.getSelectedRow(), 3)).setNacimiento(jt_naci1.getText());
            ((Tutores) model.getValueAt(estudiantes.getSelectedRow(), 4)).setNumcuenta(Integer.parseInt(jt_no1.getText()));
            ((Tutores) model.getValueAt(estudiantes.getSelectedRow(), 5)).setUsuario(jt_usua1.getText());
            ((Tutores) model.getValueAt(estudiantes.getSelectedRow(), 6)).setContraseña(jt_contra1.getText());
            ((Tutores) model.getValueAt(estudiantes.getSelectedRow(), 7)).setGanancias(Integer.parseInt(jt_apre.getText()));
            tutores.setModel(model);

        }
    }//GEN-LAST:event_jb_modificarestuMouseClicked

    private void jb_salir3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salir3MouseClicked
        // TODO add your handling code here:
        ventanaestudiante.setVisible(false);
    }//GEN-LAST:event_jb_salir3MouseClicked

    private void jb_salir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salir2MouseClicked
        // TODO add your handling code here:
        ventanatutor.setVisible(false);
    }//GEN-LAST:event_jb_salir2MouseClicked

    private void IniciarsesiontutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarsesiontutorMouseClicked
        // TODO add your handling code here:
         String usuario, contraseña;
        try {
            usuario = jt_usuario3.getText();
            contraseña = jt_contraseña3.getText();
            for (Alumnos alumnos : lista) {
                if (alumnos instanceof Tutores) {
                    if (usuario == ((Tutores) alumnos).getUsuario() && contraseña == ((Tutores) alumnos).getContraseña()) {
                        this.ventanatutor.pack();
                        ventanatutor.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "El usuario o cjontraseña no existe en tutor");
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Ocurrio un problema consulte al administrador");
        }
    }//GEN-LAST:event_IniciarsesiontutorMouseClicked

    private void jb_examMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_examMouseClicked
        // TODO add your handling code here:
        String clase,tema;
        int conocimiento,puntaje;
        try {
            clase=jt_clase.getText();
            conocimiento=Integer.parseInt(jt_cono.getText());
            tema=jt_tema.getText();
            puntaje=Integer.parseInt(jt_puntaje.getText());
           Examenes e=new Examenes(clase, conocimiento, puntaje, tema);
            for (Alumnos alumnos : lista) {
                if(alumnos instanceof Estudiante){
                ((Estudiante) alumnos).getExamenespen().add(e);
                }
            }
            jt_clase.setText("");
            jt_cono.setText("");
            jt_tema.setText("");
            jt_puntaje.setText("");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Ocurrio un error consultar al administrador examen no creado");
        }
    }//GEN-LAST:event_jb_examMouseClicked

    private void jb_tutoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_tutoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_tutoria1ActionPerformed

    private void jb_tutoria1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_tutoria1MouseClicked
        // TODO add your handling code here:
        this.Tutorias.pack();
        Tutorias.setVisible(true);
    }//GEN-LAST:event_jb_tutoria1MouseClicked

    private void jb_creartutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_creartutoMouseClicked
        // TODO add your handling code here:
        String Tema;
        Tutores t;
        Date fecha;
        int aula,hora;
        try {
            Tema=jt_tema1.getText();
            t=(Tutores)cb_tutor.getSelectedItem();
            hora=Integer.parseInt(jt_hora.getText());
            fecha=jd_fecha.getDate();
            fecha.setHours(hora);
            aula=Integer.parseInt(jt_aula.getText());
            Tutoria tut=new Tutoria(hora, aula, fecha, Tema, t);
            lista2.add(tut);
            tut.getAl().add(new Estudiante());
            DefaultComboBoxModel mo=(DefaultComboBoxModel)cb_sim.getModel();
            mo.addElement(tut);
            cb_sim.setModel(mo);
            JOptionPane.showMessageDialog(null,"Tutoria crada con exito");
                    
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Ocurrio un problema al reservar la tutoria");
        }
        
    }//GEN-LAST:event_jb_creartutoMouseClicked

    private void cb_simItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_simItemStateChanged
        // TODO add your handling code here:
      try{
        cb_sim.getSelectedItem();
        for (int i = 0; i < ((Tutoria)cb_sim.getSelectedItem()).getAl().size(); i++) {
            ((Estudiante)((Tutoria)cb_sim.getSelectedItem()).getAl().get(i)).setConocimiento(0+random.nextInt(99));
        }
        ((Tutoria)cb_sim.getSelectedItem()).getTutores().setGanancias(270);
        cb_sim.removeItem( cb_sim.getSelectedItem());
        JOptionPane.showMessageDialog(null, "Tutoria dada con exito");
      }catch(Exception e){
      e.printStackTrace();
          System.out.println("Ocurrio un error con el tutor al parecer se durmio y no llego");
      }
    }//GEN-LAST:event_cb_simItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen1DiegoVarela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen1DiegoVarela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen1DiegoVarela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen1DiegoVarela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen1DiegoVarela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Edad;
    private javax.swing.JLabel Edad1;
    private javax.swing.JFrame Estudiante;
    private javax.swing.JButton Iniciarsesionestu;
    private javax.swing.JButton Iniciarsesiontutor;
    private javax.swing.JFrame Tutorias;
    private javax.swing.JComboBox<String> cb_sim;
    private javax.swing.JComboBox<String> cb_tutor;
    private javax.swing.JTable estudiantes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_clase;
    private javax.swing.JButton jb_creartuto;
    private javax.swing.JButton jb_exam;
    private javax.swing.JButton jb_guardarestudiante;
    private javax.swing.JButton jb_inicarestudiante;
    private javax.swing.JButton jb_iniciartutor;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JButton jb_modificarestu;
    private javax.swing.JButton jb_salir;
    private javax.swing.JButton jb_salir2;
    private javax.swing.JButton jb_salir3;
    private javax.swing.JButton jb_tutoria;
    private javax.swing.JButton jb_tutoria1;
    private com.toedter.calendar.JDateChooser jd_fecha;
    private javax.swing.JTextField jt_apre;
    private javax.swing.JTextField jt_aprendizaje;
    private javax.swing.JTextField jt_aula;
    private javax.swing.JTextField jt_carr;
    private javax.swing.JTextField jt_carr1;
    private javax.swing.JTextField jt_carrera;
    private javax.swing.JTextField jt_cla;
    private javax.swing.JTextField jt_clase;
    private javax.swing.JTextField jt_cono;
    private javax.swing.JTextField jt_contra;
    private javax.swing.JTextField jt_contra1;
    private javax.swing.JTextField jt_contraseña;
    private javax.swing.JTextField jt_contraseña2;
    private javax.swing.JTextField jt_contraseña3;
    private javax.swing.JTextField jt_ed;
    private javax.swing.JTextField jt_ed1;
    private javax.swing.JTextField jt_edad;
    private javax.swing.JTextField jt_gan;
    private javax.swing.JTextField jt_hora;
    private javax.swing.JTextField jt_lugar;
    private javax.swing.JTextField jt_naci;
    private javax.swing.JTextField jt_naci1;
    private javax.swing.JTextField jt_no;
    private javax.swing.JTextField jt_no1;
    private javax.swing.JTextField jt_nom;
    private javax.swing.JTextField jt_nom1;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_numero;
    private javax.swing.JTextField jt_puntaje;
    private javax.swing.JTextField jt_tema;
    private javax.swing.JTextField jt_tema1;
    private javax.swing.JTextField jt_usua;
    private javax.swing.JTextField jt_usua1;
    private javax.swing.JTextField jt_usuario;
    private javax.swing.JTextField jt_usuario2;
    private javax.swing.JTextField jt_usuario3;
    private javax.swing.JFrame sesionestudiante;
    private javax.swing.JFrame sesiontutor;
    private javax.swing.JFrame simulartuto;
    private javax.swing.JFrame tutor;
    private javax.swing.JTable tutores;
    private javax.swing.JFrame ventanaestudiante;
    private javax.swing.JFrame ventanatutor;
    // End of variables declaration//GEN-END:variables
ArrayList<Alumnos> lista = new ArrayList();
ArrayList<Tutoria> lista2 = new ArrayList();
}
